FROM gcr.io/google.com/cloudsdktool/cloud-sdk:alpine

#default values
ARG GCP_REGION=asia-southeast1
ARG GCP_PROJECT=scg-hip-dev
ARG KAFKA_LOGIN_SECRET
ARG SECRET_NAME

ENV GCP_REGION $GCP_REGION
ENV GCP_PROJECT $GCP_PROJECT
ENV KAFKA_LOGIN_SECRET $KAFKA_LOGIN_SECRET
ENV SECRET_NAME $SECRET_NAME

ENV GOOGLE_CLOUD_CREDENTIALS /.google-credentials

ENTRYPOINT chmod +x /app/apply-secrets.sh && /app/apply-secrets.sh
